version: '3.13.3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./:/app 
    command: >
      sh -c "python -m pip install --upgrade pip &&
      pip install -r requirements.txt &&
      uvicorn app:app --host 0.0.0.0 --port 8000"